# Generated by Django 5.1.3 on 2024-11-27 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_name', models.CharField(max_length=20)),
                ('model_phone', models.CharField(max_length=100)),
                ('photo_phone', models.ImageField(blank=True, null=True, upload_to='photos')),
                ('phone_author', models.ImageField(blank=True, null=True, upload_to='photos')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.CharField(blank=True, choices=[('availble', 'availble'), ('rental', 'rental'), ('sold', 'sold'), ('phone', 'phone')], max_length=50, null=True),
        ),
    ]
