# Generated by Django 5.1.3 on 2025-01-26 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0004_alter_book_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='photo_phone',
            field=models.ImageField(blank=True, null=True, upload_to='phonos/'),
        ),
    ]
