# Generated by Django 5.1.3 on 2025-01-26 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0005_alter_phone_photo_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='photo_phone',
            field=models.ImageField(blank=True, null=True, upload_to='photos'),
        ),
    ]
