# Generated by Django 5.1.3 on 2025-01-27 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0007_categoryphone_alter_book_status_phone_the_condition'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='Phone_status',
            field=models.CharField(blank=True, choices=[('Flagship', 'Flagship'), ('Gaming Phones', 'Gaming Phones'), ('Foldable Phones', 'Foldable Phones')], max_length=50, null=True),
        ),
    ]
