# Generated by Django 5.1.3 on 2025-01-27 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0008_phone_phone_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='phone_name',
            field=models.CharField(max_length=50),
        ),
    ]
