# Generated by Django 5.1.3 on 2025-02-01 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0010_alter_book_photo_author_alter_book_photo_book_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='total_rental',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='phone',
            name='active_name',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='photo_author',
            field=models.ImageField(blank=True, null=True, upload_to='photos'),
        ),
        migrations.AlterField(
            model_name='book',
            name='photo_book',
            field=models.ImageField(blank=True, null=True, upload_to='photos'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='phone_author',
            field=models.ImageField(blank=True, null=True, upload_to='photos'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='photo_phone',
            field=models.ImageField(blank=True, null=True, upload_to='photos'),
        ),
    ]
