# Generated by Django 5.1.3 on 2025-02-01 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0011_book_total_rental_phone_active_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='retal_period',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
